const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("🗳️  Deploying EVoting Smart Contract...\n");
  const [deployer] = await hre.ethers.getSigners();
  console.log(`📋 Deployer Address: ${deployer.address}`);

  const EVoting = await hre.ethers.getContractFactory("EVoting");
  const evoting = await EVoting.deploy("YMCA Student election 2026");
  await evoting.waitForDeployment();
  const contractAddress = await evoting.getAddress();
  console.log(`✅ Deployed at: ${contractAddress}\n`);

  const candidates = [
    { name: "Arjun Sharma",  party: "Progressive Alliance",  description: "Committed to digital infrastructure and transparent governance." },
    { name: "Priya Verma",   party: "National Reform Party", description: "Focused on education reforms and rural development." },
    { name: "Rohan Mehta",   party: "United Front",          description: "Advocate for youth empowerment and economic growth." },
    { name: "Kavya Nair",    party: "Green India Party",     description: "Champion of sustainable development and climate action." },
  ];

  for (const c of candidates) {
    const tx = await evoting.addCandidate(c.name, c.party, c.description);
    await tx.wait();
    console.log(`  ✓ Added: ${c.name}`);
  }

  const startTx = await evoting.startElection(90);
  await startTx.wait();
  console.log("\n✅ Election ACTIVE (90 min)");

  const artifactPath = path.join(__dirname, "../artifacts/contracts/EVoting.sol/EVoting.json");
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));

  const frontendConfigPath = path.join(__dirname, "../../frontend/src/utils/contractConfig.js");
  const backendConfigPath  = path.join(__dirname, "../../backend/contractConfig.json");

  fs.writeFileSync(frontendConfigPath,
    `// AUTO-GENERATED by deploy.js\nexport const CONTRACT_ADDRESS = "${contractAddress}";\nexport const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};\n`
  );
  fs.writeFileSync(backendConfigPath, JSON.stringify({ CONTRACT_ADDRESS: contractAddress, ABI: artifact.abi }, null, 2));

  console.log(`\n📄 Config written to frontend and backend`);
  console.log(`\nContract Address: ${contractAddress}`);
}

main().catch((err) => { console.error(err); process.exit(1); });
